' ExportBoatParams.bas -- Sailbench boat-parameter dump
'
' Run against the OPEN "Full Boat Assembly" in SolidWorks (Windows).
'   Tools > Macro > New...   (save as ExportBoatParams.swp)
'   paste this whole file over the empty module, then Run.
'
' Writes boat_params.yaml next to the assembly: total mass, CG, the full
' inertia tensor at the CG, and the mass + CG of every top-level component
' (all in ASSEMBLY output coordinates, kg and metres).
'
' Component CGs come out in assembly coordinates because GetMassProperties
' honours the current selection -- each component is selected in turn, so no
' transform math is needed.

Option Explicit

Dim swApp As Object
Dim swModel As Object
Dim swExt As Object
Dim swSelMgr As Object

Sub main()

    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc

    If swModel Is Nothing Then
        MsgBox "Open the boat assembly first, then run the macro."
        Exit Sub
    End If

    Set swExt = swModel.Extension
    Set swSelMgr = swModel.SelectionManager

    Dim outPath As String
    outPath = OutFilePath(swModel)

    Dim f As Integer
    f = FreeFile
    Open outPath For Output As #f

    Print #f, "# generated by ExportBoatParams.bas from " & swModel.GetTitle
    Print #f, "# units: kg, m, kg*m^2 -- inertia taken AT THE CG, aligned with"
    Print #f, "# the assembly output coordinate system (X/Y/Z as shown in the"
    Print #f, "# SolidWorks Mass Properties dialog)."
    Print #f, ""

    swSelMgr.SuspendSelectionList
    swModel.ClearSelection2 True

    Dim tot As Variant
    tot = MassProps()
    If IsEmpty(tot) Then
        Close #f
        MsgBox "Mass properties failed on the top-level document."
        Exit Sub
    End If

    Print #f, "total:"
    WriteProps f, "  ", tot

    ' 2 = assembly document
    If swModel.GetType = 2 Then
        Print #f, ""
        Print #f, "components:"

        Dim comps As Variant
        comps = swModel.GetComponents(True)   ' True = top level only

        Dim i As Long
        For i = 0 To UBound(comps)
            Dim comp As Object
            Set comp = comps(i)

            ' 0 = fully suppressed
            If comp.GetSuppression <> 0 And comp.IsEnvelope = False Then
                swModel.ClearSelection2 True
                comp.Select4 False, Nothing, False

                Dim cp As Variant
                cp = MassProps()

                Print #f, "  - name: """ & comp.Name2 & """"
                If IsEmpty(cp) Then
                    Print #f, "    error: mass properties unavailable"
                Else
                    WriteProps f, "    ", cp
                End If
            End If
        Next i
    End If

    swModel.ClearSelection2 True
    swSelMgr.ResumeSelectionList

    Close #f

    MsgBox "Wrote " & outPath

End Sub

' GetMassProperties returns, in system units:
'   0,1,2 = CG x,y,z   3 = volume   4 = surface area   5 = mass
'   6..11 = Lxx, Lyy, Lzz, Lxy, Lzx, Lyz  (about the CG)
Private Function MassProps() As Variant

    Dim status As Long
    Dim v As Variant

    On Error Resume Next
    v = swExt.GetMassProperties2(1, status, True)
    On Error GoTo 0

    If IsEmpty(v) Then v = swExt.GetMassProperties(1, status)

    MassProps = v

End Function

Private Sub WriteProps(ByVal f As Integer, ByVal pad As String, ByVal v As Variant)

    Print #f, pad & "mass_kg: " & Num(v(5))
    Print #f, pad & "volume_m3: " & Num(v(3))
    Print #f, pad & "surface_area_m2: " & Num(v(4))
    Print #f, pad & "cg_m: [" & Num(v(0)) & ", " & Num(v(1)) & ", " & Num(v(2)) & "]"
    Print #f, pad & "inertia_at_cg_kg_m2:"
    Print #f, pad & "  Lxx: " & Num(v(6))
    Print #f, pad & "  Lyy: " & Num(v(7))
    Print #f, pad & "  Lzz: " & Num(v(8))
    Print #f, pad & "  Lxy: " & Num(v(9))
    Print #f, pad & "  Lzx: " & Num(v(10))
    Print #f, pad & "  Lyz: " & Num(v(11))

End Sub

' Invariant decimal point, 6 significant-ish digits, no locale commas.
Private Function Num(ByVal x As Double) As String

    Dim s As String
    s = Format(x, "0.000000")
    Num = Replace(s, ",", ".")

End Function

Private Function OutFilePath(ByVal model As Object) As String

    Dim p As String
    p = model.GetPathName

    If Len(p) = 0 Then
        OutFilePath = Environ$("USERPROFILE") & "\Desktop\boat_params.yaml"
    Else
        OutFilePath = Left$(p, InStrRev(p, "\")) & "boat_params.yaml"
    End If

End Function
